### ISSUE TITLE
一登录邮箱帐号程序就崩溃

### ISSUE THREAD

**Issue by liuhangbin** [cosven/FeelUOwn#102]
[INFO] [api.py line:36] : method=POST_UPDATE url=http://music.163.com/api/login/ query={'username': 'my_account@163.com', 'password': '*******', 'rememberLogin': 'true'}
[INFO] [connectionpool.py line:207] : Starting new HTTP connection (1): music.163.com
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/feeluown/widgets/login_dialog.py", line 117, in __login
    data = self.ne.login(username, password, phone_login)
  File "/usr/lib/python3.4/site-packages/feeluown/plugin/NetEaseMusic/normalize.py", line 91, in login
    data = self.access_data_user(data)
  File "/usr/lib/python3.4/site-packages/feeluown/plugin/NetEaseMusic/normalize.py", line 418, in access_data_user
    user_data['avatar'] = user_data['profile']['avatarUrl']
KeyError: 'profile'
/usr/bin/feeluown: line 2:  4680 Aborted                 (core dumped) python3 /usr/lib/python3.4/site-packages/feeluown/main.py

$ uname -r
4.3.5-300.fc23.x86_64
$ rpm -q feeluown
feeluown-7.0-0.1.git4fae2af.fc23.noarch

**Comment by liuhangbin** [comment]
找到问题了，以前没登录过，没有设置帐号的profile...
