### ISSUE TITLE
2月update 后无法启动

### ISSUE THREAD

**Issue by imysl0** [cosven/FeelUOwn#104]
今天update后无法启动：
Traceback (most recent call last):
  File "/home/～/SOFT/FeelUOwn/feeluown/main.py", line 31, in <module>
    from feeluown import config
  File "../feeluown/__init__.py", line 3, in <module>
    from .config import config
  File "../feeluown/config.py", line 5, in <module>
    import yaml
ImportError: No module named 'yaml'

更新前是可以正常使用的，update完后报这个：
install pip for python3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
---------------------------
生成桌面图标
猜测：中文系统
生成系统图标
===============================
好消息：您已经安装了 VLC 播放器
全部完成!

**Comment by cosven** [comment]
你的问题实际上就是没办法安装 `pip3`
解决办法是： `easy_install3 pip`

**Comment by imysl0** [comment]
works! Great, thanks~~~
