### ISSUE TITLE
歌名显示"口口".

### ISSUE THREAD

**Issue by abcfy2** [cosven/FeelUOwn#109]
![image](https://cloud.githubusercontent.com/assets/5327677/13311159/18b16f28-dbc7-11e5-8e4b-ba7c7afaa101.png)

终端下运行还有一段报错:
```
[INFO] [normalize.py line:218] : update user playlists info
[ERROR] [__init__.py line:597] : Exception in callback NetEaseAPI.get_playlist_detail(123056695)
handle: <Handle NetEaseAPI.get_playlist_detail(123056695)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 182, in get_playlist_detail
    if PlaylistDb.exists(pid):
  File "../feeluown/plugin/NetEaseMusic/model.py", line 42, in exists
    if ControllerApi.session.query(cls).filter(cls.pid==pid).count() > 0:
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2790, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2559, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2528, in one
    ret = list(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
    **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 202, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
[INFO] [api.py line:36] : method=POST url=http://music.163.com/api/search/get query={'s': '灵剑山', 'type': 1, 'limit': 60, 'offset': 0, 'total': 'true'}
[INFO] [connectionpool.py line:264] : Starting new HTTP connection (1): music.163.com

```

**Comment by cosven** [comment]
这个报错暂时没什么影响。
#1 乱码的问题暂时还不知道怎样解决，不过中文系统貌似不会有这个问题...(另外，我Ubuntu 15.10英文也不会又乱码)

**Comment by abcfy2** [comment]
的确如issue 1所述，日文乱码，我尝试安装了所有的wqy字体(`apt-get install '.*wqy.*'`)，但是并没有效果。应该是fallback到了一个不支持日文的字体上，但是列表中的音乐却没事。

**Comment by abcfy2** [comment]
有所发现，怀疑是调用系统默认字体。

我调整了一下系统默认字体(Linux Mint 17.3)，换了一个CJK字体(noto sans cjk)，如图所示
![image](https://cloud.githubusercontent.com/assets/5327677/13311514/0316b3dc-dbca-11e5-88f6-da68c07850f8.png)

然后重启feeluown，列表和播放都正常了(列表字体也和以前稍微不同了):
![image](https://cloud.githubusercontent.com/assets/5327677/13311527/184fe17e-dbca-11e5-979e-77f9f3e86318.png)

**Comment by abcfy2** [comment]
诡异了，可能不是这个问题。重新打开了一下，发现又变成"口口"了。再研究研究

**Comment by abcfy2** [comment]
神奇的问题，我从终端下运行了一次，发现是OK的。再次从桌面图标打开运行，发现也是OK的。这个问题居然成了一个随机出现的问题了= =。难道fallback的字体还是随机的么？
