### ISSUE TITLE
ubuntu 15.10 下点击播放没反应，所有依赖都已安装

### ISSUE THREAD

**Issue by kylingit** [cosven/FeelUOwn#123]
`[INFO] [connectionpool.py line:205] : Starting new HTTP connection (1): music.163.com
[ERROR] [__init__.py line:597] : Exception in callback NetEaseAPI.get_playlist_detail(117964019)
handle: <Handle NetEaseAPI.get_playlist_detail(117964019)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 191, in get_playlist_detail
    return self.update_playlist_detail(pid)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 166, in update_playlist_detail
    data['tracks'][i] = self.access_music(track)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 411, in access_music
    song = MusicModel(music_data).get_dict()
  File "../feeluown/models.py", line 74, in __init__
    self.init_model()
  File "../feeluown/models.py", line 22, in init_model
    if self.validate() is True:
  File "../feeluown/models.py", line 36, in validate
    raise TypeError('Please check your object type: ', key)
TypeError: ('Please check your object type: ', 'album')
`
运行app.sh出现这样的错误，请问如何解决？

**Comment by BruceZhang1993** [comment]
应该只是网络的问题吧，你是不是用国外IP~~

**Comment by cosven** [comment]
老的 ISSUE , 就关闭了。新版貌似没这个问题
