### ISSUE TITLE
Archlinux上运行失败

### ISSUE THREAD

**Issue by seasonyuu** [cosven/FeelUOwn#133]
```
FeelUOwn
Traceback (most recent call last):
  File "/usr/share/feeluown-git/feeluown/main.py", line 34, in <module>
    from feeluown.glue import Glue
  File "../feeluown/glue.py", line 16, in <module>
    from feeluown.network_manager import NetworkManager
  File "../feeluown/network_manager.py", line 5, in <module>
    from PyQt5.QtNetwork import QNetworkAccessManager, QNetworkReply
ImportError: /usr/lib/libQt5Network.so.5: undefined symbol: SSLv2_client_method
```
通过<code>yaourt -S feeluown-git</code>方式安装

**Comment by wenLiangcan** [comment]
我也是这样安装的，没有这个问题。你的系统最近有更新过么？没有的话试试更新一下？

**Comment by seasonyuu** [comment]
前天才装的系统呢…

**Comment by cosven** [comment]
<https://bugzilla.redhat.com/show_bug.cgi?id=1313509>
目测是上游一些包的问题。

**Comment by seasonyuu** [comment]
是的 已解决
