### ISSUE TITLE
Fedora 22 登录时闪退

### ISSUE THREAD

**Issue by monkey2000** [cosven/FeelUOwn#143]
Traceback (most recent call last):
          File "../feeluown/widgets/login_dialog.py", line 117, in __login
            data = self.ne.login(username, password, phone_login)
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 93, in login
            self._on_login_success()
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 111, in _on_login_success
            self.save_cookies()
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 68, in save_cookies
            user.update(_cookies=pickle.dumps(self.ne.cookies))
          File "../feeluown/plugin/NetEaseMusic/model.py", line 125, in update
            .filter(UserDb.id==self.id).update(kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2851, in update
            update_op.exec_()
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 926, in exec_
            self._do_exec()
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1027, in _do_exec
            update_stmt, params=self.query._params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 1022, in execute
            bind, close_with_result=True).execute(clause, params or {})
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 841, in execute
            return meth(self, multiparams, params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
            return connection._execute_clauseelement(self, multiparams, params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 931, in _execute_clauseelement
            inline=len(distilled_params) > 1)
          File "<string>", line 1, in <lambda>
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 493, in compile
            return self._compiler(dialect, bind=bind, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 499, in _compiler
            return dialect.statement_compiler(dialect, self, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 395, in __init__
            Compiled.__init__(self, dialect, statement, **kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 199, in __init__
            self.string = self.process(self.statement, **compile_kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 222, in process
            return obj._compiler_dispatch(self, **kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 80, in _compiler_dispatch
            return meth(self, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1831, in visit_update
            colparams = self._get_colparams(update_stmt, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 2242, in _get_colparams
            (", ".join("%s" % c for c in check))
        sqlalchemy.exc.CompileError:         Traceback (most recent call last):
          File "../feeluown/widgets/login_dialog.py", line 117, in __login
            data = self.ne.login(username, password, phone_login)
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 93, in login
            self._on_login_success()
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 111, in _on_login_success
            self.save_cookies()
          File "../feeluown/plugin/NetEaseMusic/normalize.py", line 68, in save_cookies
            user.update(_cookies=pickle.dumps(self.ne.cookies))
          File "../feeluown/plugin/NetEaseMusic/model.py", line 125, in update
            .filter(UserDb.id==self.id).update(kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/query.py", line 2851, in update
            update_op.exec_()
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 926, in exec_
            self._do_exec()
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1027, in _do_exec
            update_stmt, params=self.query._params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 1022, in execute
            bind, close_with_result=True).execute(clause, params or {})
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 841, in execute
            return meth(self, multiparams, params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
            return connection._execute_clauseelement(self, multiparams, params)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 931, in _execute_clauseelement
            inline=len(distilled_params) > 1)
          File "<string>", line 1, in <lambda>
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 493, in compile
            return self._compiler(dialect, bind=bind, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 499, in _compiler
            return dialect.statement_compiler(dialect, self, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 395, in __init__
            Compiled.__init__(self, dialect, statement, **kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 199, in __init__
            self.string = self.process(self.statement, **compile_kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 222, in process
            return obj._compiler_dispatch(self, **kwargs)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/visitors.py", line 80, in _compiler_dispatch
            return meth(self, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 1831, in visit_update
            colparams = self._get_colparams(update_stmt, **kw)
          File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/compiler.py", line 2242, in _get_colparams
            (", ".join("%s" % c for c in check))
        sqlalchemy.exc.CompileError: Unconsumed column names: _cookies

使用FZUG源安装的播放器
为啥会出 `Unconsumed column names: _cookies` 呢

**Comment by monkey2000** [comment]
使用FZUG Repo安装的播放器

**Comment by cosven** [comment]
这个问题之前没遇到过，我暂时也不知道为啥。现在我主要精力都花在新开发版上，建议您也尝试尝试新的版本（在 dev 分支上）。

**Comment by monkey2000** [comment]
Dev版本有同样问题，我自己看看能不能修一下好了。
