### ISSUE TITLE
打开后 没有反应

### ISSUE THREAD

**Issue by ker0491** [cosven/FeelUOwn#150]
![2016-05-11 22-31-42](https://cloud.githubusercontent.com/assets/5814174/15184578/598b9478-17c8-11e6-96d4-31eaa84cb1d0.png)

k@k-Aspire-E1-471G:~/FeelUOwn$ make run
python3 -m feeluown -d
[ERROR] [plugin.py line:40] : detect a bad plugin neteasemusic
Traceback (most recent call last):
  File "/home/k/FeelUOwn/feeluown/plugin.py", line 34, in scan
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./feeluown/plugins/neteasemusic/__init__.py", line 5, in <module>
    from .nem import Nem
  File "./feeluown/plugins/neteasemusic/nem.py", line 9, in <module>
    from .model import NUserModel, NSongModel
  File "./feeluown/plugins/neteasemusic/model.py", line 7, in <module>
    from .api import api
  File "./feeluown/plugins/neteasemusic/api.py", line 19, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'
[INFO] [version.py line:18] : 正在查找新版本...
[INFO] [connectionpool.py line:760] : Starting new HTTPS connection (1): api.github.com

**Comment by cosven** [comment]
运行  `pip3 install pycrypto`
漏了一个 依赖库。

**Comment by ker0491** [comment]
好赞！
