### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by bdbai** [cosven/FeelUOwn#165]
今天刚刚从仓库里 pull 下来 `make install` 的，安装顺利，运行 `feeluown` 就报错：

```bash
bdbai@linux-o812:~/github/FeelUOwn> feeluown
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 9, in <module>
    load_entry_point('feeluown==1.0.3.4', 'console_scripts', 'feeluown')()
  File "/usr/lib/python3.4/site-packages/feeluown-1.0.3.4-py3.4.egg/feeluown/__main__.py", line 51, in main
    app_event_loop = QEventLoop(q_app)
  File "/usr/lib/python3.4/site-packages/Quamash-0.5.5-py3.4.egg/quamash/__init__.py", line 242, in __init__
  File "/usr/lib/python3.4/site-packages/Quamash-0.5.5-py3.4.egg/quamash/_unix.py", line 195, in __init__
  File "/usr/lib64/python3.4/asyncio/unix_events.py", line 40, in __init__
    super().__init__(selector)
  File "/usr/lib64/python3.4/asyncio/selector_events.py", line 39, in __init__
    self._make_self_pipe()
  File "/usr/lib64/python3.4/asyncio/selector_events.py", line 81, in _make_self_pipe
    self.add_reader(self._ssock.fileno(), self._read_from_self)
  File "/usr/lib/python3.4/site-packages/Quamash-0.5.5-py3.4.egg/quamash/__init__.py", line 364, in add_reader
AttributeError: 'QEventLoop' object has no attribute '_check_closed'
```

系统是 openSUSE Leap，请问怎么解决？

**Comment by cosven** [comment]
跟这个 #162 一模一样的问题， suse 系统好奇怪。

**Comment by bdbai** [comment]
@cosven 我发现系统里面的 asyncio 缺了不少东西，补全以后就好了，多谢耐心提醒。在安装依赖时提醒一下其它 openSUSE 用户如何？

**Comment by cosven** [comment]
恩，确实，感觉 suse 的 asyncio 有问题。

看了几天没动静，还以为解决了，今天下午的时候就 close 这个 issue 了。

**Comment by bdbai** [comment]
@cosven 好勤快 :) 希望每日推荐早日上线

**Comment by cosven** [comment]
每日推荐不是已经有了么.

**Comment by cosven** [comment]
pip3 install feeluown --upgrade 试试？

**Comment by bdbai** [comment]
Oops...下次我去更新看看
