### ISSUE TITLE
更新时的问题

### ISSUE THREAD

**Issue by RanchoCooper** [cosven/FeelUOwn#183]
可以正常使用, 
不过现在的界面是这样的, 好像少了一些(包括登陆之后还有右侧的登陆)

![2016-06-03 13 27 23](https://cloud.githubusercontent.com/assets/15610629/15769587/12fb6ba4-298f-11e6-84f1-3dbf928791dd.png)

但pip3 install feeluown --upgrade时如下

```

Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Can't roll back requests; was not uninstalled
Cleaning up...
  Removing temporary dir /tmp/pip_build_rancho...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/requests-2.10.0.dist-info'

```

**Comment by cosven** [comment]
sudo -H pip3 install feeluown --upgrade
上面提示说没有权
