### ISSUE TITLE
there is no login icon

### ISSUE THREAD

**Issue by ghost** [cosven/FeelUOwn#186]
i install feeluown successfully on the fedora 23
`$ sudo dnf install feeluown`

but cannot find the icon of login after start it, is there any solution?

![screenshot from 2016-06-10 10-00-33](https://cloud.githubusercontent.com/assets/16489480/15952532/5e8a345a-2ef4-11e6-8711-e5d63d64fbe8.png)

**Comment by BruceZhang1993** [comment]
netease music not loaded

show some  console error output, use --debug

**Comment by laijianjia** [comment]
```
[root@fedora laijianjia]# feeluown --debug
Qt: Session management error: None of the authentication protocols specified are supported
```

**Comment by laijianjia** [comment]
if i run feeluown by command as user, there is even nothing error message.

**Comment by BruceZhang1993** [comment]
@laijianjia you should not use feeluown under root user console

see this -> [http://zhubangbing.blog.163.com/blog/static/526092702011213105435552/](url)
and this -> [http://www.linuxforums.org/forum/programming-scripting/148883-solved-session-management-error-authentication-rejected.html](url)

**Comment by laijianjia** [comment]
@BruceZhang1993 i also try non-root user, but there is nothing error message, no matter it is running or closing. btw, the two pages you give are missing.
![screenshot from 2016-06-10 14-13-20](https://cloud.githubusercontent.com/assets/16489480/15955682/d0538930-2f15-11e6-8191-4d124b9c2506.png)

**Comment by BruceZhang1993** [comment]
@laijianjia  '  feeluown -d ' will dump all debug msg to console
 try it

**Comment by laijianjia** [comment]
```
[laijianjia@fedora ~]$ feeluown -d 
Exception ignored in: <bound method QEventLoop.__del__ of <QEventLoop running=False closed=False debug=False>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/base_events.py", line 361, in __del__
  File "/usr/lib/python3.4/site-packages/quamash/__init__.py", line 300, in close
  File "/usr/lib64/python3.4/logging/__init__.py", line 1262, in debug
  File "/usr/lib64/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib64/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib64/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib64/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib64/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib64/python3.4/logging/__init__.py", line 1030, in _open
NameError: name 'open' is not defined
```

**Comment by BruceZhang1993** [comment]
@laijianjia 
that is strange..   open() is just a built-in function.  
maybe something wrong with your python installation~

**Comment by chunws** [comment]
I had the same situation on the Ubuntu 16.04
I solved it by `pip3 install pycrypto `

**Comment by xuhao148** [comment]
I have the same problem but I have upgraded my Python from 3.4 to 3.5.
Here is the log:
`Exception ignored in: <bound method BaseEventLoop.__del__ of <QEventLoop running=False closed=False debug=False>>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 381, in __del__
  File "/usr/lib64/python3.5/site-packages/quamash/__init__.py", line 300, in close
  File "/usr/lib64/python3.5/logging/__init__.py", line 1267, in debug
  File "/usr/lib64/python3.5/logging/__init__.py", line 1415, in _log
  File "/usr/lib64/python3.5/logging/__init__.py", line 1425, in handle
  File "/usr/lib64/python3.5/logging/__init__.py", line 1487, in callHandlers
  File "/usr/lib64/python3.5/logging/__init__.py", line 855, in handle
  File "/usr/lib64/python3.5/logging/__init__.py", line 1047, in emit
  File "/usr/lib64/python3.5/logging/__init__.py", line 1037, in _open
NameError: name 'open' is not defined
`
