### ISSUE TITLE
No such file or directory: '/home/username/.FeelUOwn/feeluown.png'

### ISSUE THREAD

**Issue by qinhuan** [cosven/FeelUOwn#192]
When I run ./install.py, there is a bug, 
Traceback (most recent call last):
  File "./install.py", line 90, in <module>
    generate_icon()
  File "./install.py", line 51, in generate_icon
    shutil.copy(icon, feeluown_icon)
  File "/usr/lib/python3.4/shutil.py", line 229, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 109, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.FeelUOwn/feeluown.png'

How to solve it?

**Comment by qinhuan** [comment]
Sorry, it's a easy problem. I shouldn't ask this question.
I view the source code of install.py, and the following operations will solve the problem.
cd /home/username
mkdir .FeelUOwn
And it's OK.

**Comment by qinhuan** [comment]
shabi'me didn't have a look at README.md .....
