### ISSUE TITLE
crash when login to netease

### ISSUE THREAD

**Issue by bruceauyeung** [cosven/FeelUOwn#210]
feeluown : feeluown-git 1:9.3a.0.g698ed58-1 from aur
os: manjaro
feeluown poped up a login window, so i typed in netease user name and password, but after clicking login button, feeluown crashed.
>$ feeluown 
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-45: ordinal not in range(128)
Call stack:
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/feeluown/__main__.py", line 55, in main
    app = App()
  File "/usr/lib/python3.5/site-packages/feeluown/app.py", line 45, in __init__
    self._init_managers()
  File "/usr/lib/python3.5/site-packages/feeluown/app.py", line 117, in _init_managers
    self.plugins_manager.scan()
  File "/usr/lib/python3.5/site-packages/feeluown/plugin.py", line 38, in scan
    logger.info('detect plugin: %s.' % plugin_name)
Message: 'detect plugin: \u7f51\u6613\u4e91\u97f3\u4e50.'
Arguments: ()
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 133, in login
    self.user = NUserModel.create(data)
  File "./feeluown/plugins/neteasemusic/model.py", line 372, in create
    img = user_data['profile']['avatarUrl']
KeyError: 'profile'
/usr/bin/feeluown: line 2:  5144 Aborted                 (core dumped) python -c 'from feeluown import __main__ as fu;fu.main()' "$@"

**Comment by cosven** [comment]
你这个是不是新用户，需要在网页版先设置一下个人信息 ~

**Comment by shockwavemoto** [comment]
>$ feeluown
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/init.py", line 982, in emit
stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-45: ordinal not in range(128)
Call stack:
File "", line 1, in 
File "/usr/lib/python3.5/site-packages/feeluown/main.py", line 55, in main
app = App()
File "/usr/lib/python3.5/site-packages/feeluown/app.py", line 45, in init
self._init_managers()
File "/usr/lib/python3.5/site-packages/feeluown/app.py", line 117, in _init_managers
self.plugins_manager.scan()
File "/usr/lib/python3.5/site-packages/feeluown/plugin.py", line 38, in scan
logger.info('detect plugin: %s.' % plugin_name)
Message: 'detect plugin: \u7f51\u6613\u4e91\u97f3\u4e50.'
Arguments: ()
Traceback (most recent call last):
File "./feeluown/plugins/neteasemusic/nem.py", line 133, in login
self.user = NUserModel.create(data)
File "./feeluown/plugins/neteasemusic/model.py", line 372, in create
img = user_data['profile']['avatarUrl']
KeyError: 'profile'
/usr/bin/feeluown: line 2: 5144 Aborted (core dumped) python -c 'from feeluown import main as fu;fu.main()' "$@"

It is possible that it is a unicode error and might be sorted out with 
`#-*- coding: utf-8 -*-
`

**Comment by cosven** [comment]
你这个是不是新用户，需要在网页版先设置一下个人信息 ~ @shockwavemoto
