### ISSUE TITLE
Core dump while logging in

### ISSUE THREAD

**Issue by BruceZhang1993** [cosven/FeelUOwn#219]
Distro: Arch Linux x86_64 Rolling
Python Version: 3.6
Error module: Crypto
Debug Msg:

> Icon theme "elementary" not found.
Icon theme "gnome" not found.
[INFO] [__init__ enable 59] : neteasemusic plugin enabled
[INFO] [plugin scan 38] : detect plugin: 网易云音乐.
[ERROR] [plugin scan 40] : detect a bad plugin feeluown-mpris2-plugin
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/feeluown/plugin.py", line 37, in scan
    module.enable(self._app)
  File "./feeluown/plugins/feeluown-mpris2-plugin/__init__.py", line 19, in enable
    MprisServer(app)
  File "./feeluown/plugins/feeluown-mpris2-plugin/service.py", line 27, in __init__
    self._app.player.signal_player_media_changed.connect(
AttributeError: 'Player' object has no attribute 'signal_player_media_changed'
[INFO] [server run 40] : server run in 8000
[INFO] [version check_release 18] : 正在查找新版本...
[INFO] [request get 22] : request.get ('https://api.github.com/repos/cosven/FeelUOwn/releases',) {'timeout': 5}
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 127, in login
    data = NUserModel.check(user_data['username'], user_data['password'])
  File "./feeluown/plugins/neteasemusic/model.py", line 381, in check
    data = cls._api.login(username, pw)
  File "./feeluown/plugins/neteasemusic/api.py", line 135, in login
    payload = self.encrypt_request(data)
  File "./feeluown/plugins/neteasemusic/api.py", line 404, in encrypt_request
    self._aes_encrypt(text, first_aes_key).decode('ascii'),
  File "./feeluown/plugins/neteasemusic/api.py", line 381, in _aes_encrypt
    encryptor = AES.new(key, 2, '0102030405060708')
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 264, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 232, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 131, in _create_base_cipher
    expect_byte_string(key)
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 175, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code

**Comment by cosven** [comment]
稍等，我现在一下...

**Comment by cosven** [comment]
>[ERROR] [plugin scan 40] : detect a bad plugin feeluown-mpris2-plugin
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/feeluown/plugin.py", line 37, in scan
module.enable(self._app)
File "./feeluown/plugins/feeluown-mpris2-plugin/init.py", line 19, in enable
MprisServer(app)
File "./feeluown/plugins/feeluown-mpris2-plugin/service.py", line 27, in init
self._app.player.signal_player_media_changed.connect(
AttributeError: 'Player' object has no attribute 'signal_player_media_changed'

这个问题，你更新一下 feeluown-mpris2-plugin 这个插件，我刚修复了

另外个问题，你可以尝试拉一下最新的 feeluown 版本或者 master 代码...

**Comment by BruceZhang1993** [comment]
> 这个问题，你更新一下 feeluown-mpris2-plugin 这个插件，我刚修复了

@cosven feeluown-mpris2-plugin r7.ecac35e 插件已经是最新 commit 了，但插件依然报错

**Comment by FindHao** [comment]
```
  File "/usr/local/lib/python3.5/dist-packages/Crypto/Util/_raw_api.py", line 194, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code

```

**Comment by maz-1** [comment]
https://stackoverflow.com/questions/46052752/using-aes-encrypt-get-raise-typeerroronly-byte-strings-can-be-passed-to-c-code
python-crypto被python-pycryptodemo取代了，参数类型变了

**Comment by cosven** [comment]
最新的开发版本已经用 pycryptodome 取代了
