### ISSUE TITLE
播放时崩溃

### ISSUE THREAD

**Issue by wenLiangcan** [cosven/FeelUOwn#220]
```
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 168, in play_all
    self._app.player.set_music_list(songs_table.songs)
  File "/usr/lib/python3.6/site-packages/feeluown/player.py", line 136, in set_music_list
    self.play(self._music_list[0])
  File "/usr/lib/python3.6/site-packages/feeluown/player.py", line 170, in play
    self._play(music_model)
  File "/usr/lib/python3.6/site-packages/feeluown/player.py", line 160, in _play
    self.player.play(self.current_song.url)
  File "./feeluown/plugins/neteasemusic/model.py", line 80, in url
    data = self._api.weapi_songs_url([self.mid])
  File "./feeluown/plugins/neteasemusic/api.py", line 276, in weapi_songs_url
    payload = self.encrypt_request(data)
  File "./feeluown/plugins/neteasemusic/api.py", line 404, in encrypt_request
    self._aes_encrypt(text, first_aes_key).decode('ascii'),
  File "./feeluown/plugins/neteasemusic/api.py", line 381, in _aes_encrypt
    encryptor = AES.new(key, 2, '0102030405060708')
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 264, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 232, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 131, in _create_base_cipher
    expect_byte_string(key)
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 175, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code
```

**Comment by cosven** [comment]
尝试修复了下 ~

**Comment by wenLiangcan** [comment]
还是出错　　

```
Traceback (most recent call last):
  File "./feeluown/plugins/neteasemusic/nem.py", line 163, in play_song
    self._app.player.play(song)
  File "/usr/lib/python3.6/site-packages/feeluown/player.py", line 170, in play
    self._play(music_model)
  File "/usr/lib/python3.6/site-packages/feeluown/player.py", line 160, in _play
    self.player.play(self.current_song.url)
  File "./feeluown/plugins/neteasemusic/model.py", line 80, in url
    data = self._api.weapi_songs_url([self.mid])
  File "./feeluown/plugins/neteasemusic/api.py", line 276, in weapi_songs_url
    payload = self.encrypt_request(data)
  File "./feeluown/plugins/neteasemusic/api.py", line 404, in encrypt_request
    self._aes_encrypt(text, first_aes_key).decode('ascii'),
  File "./feeluown/plugins/neteasemusic/api.py", line 381, in _aes_encrypt
    encryptor = AES.new(bytes(key, 'utf-8'), 2, '0102030405060708')
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 264, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 247, in _create_cbc_cipher
    return CbcMode(cipher_state, iv)
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 93, in __init__
    expect_byte_string(iv)
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 175, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code
```

**Comment by cosven** [comment]
刚让朋友用 ubuntu 16.04 python3.5 测试了下，他说没问题了 ~
不知道有木有 fix 掉

**Comment by wenLiangcan** [comment]
看了一下修改的代码，这个方法我自己试过一下，修改后会报另外一个错误，今晚回去贴一下出来

**Comment by cosven** [comment]
恩，我今天装个虚拟机试一下吧 ~

**Comment by cosven** [comment]
ummm
装了个虚拟机，用 python3.6.1 最新版 feeluown 1.1.0a2 测试 -> 不能复现问题

然后 clone master 分支进行测试 -> 也不能复现问题

然后之前的 fix 中是加上了 `b'0102....'`，但是去掉 b 和 加上 b 都是没有问题的

**Comment by cosven** [comment]
感觉可以重装 pycrypto 试试

**Comment by wenLiangcan** [comment]
重装 pycrypto 可以了，非常感谢。

**Comment by FindHao** [comment]
同样的错误，尝试卸载pycrypto：

```
sudo pip3 uninstall pycrypto
Cannot uninstall 'pycrypto'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Debian 9
