### ISSUE TITLE
osx运行报错

### ISSUE THREAD

**Issue by a289459798** [cosven/FeelUOwn#226]
Traceback (most recent call last):
  File "/usr/local/bin/feeluown", line 11, in <module>
    load_entry_point('feeluown==1.1.0', 'console_scripts', 'feeluown')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/feeluown-1.1.0-py3.6.egg/feeluown/__main__.py", line 12, in <module>
    from feeluown.app import App
  File "/usr/local/lib/python3.6/site-packages/feeluown-1.1.0-py3.6.egg/feeluown/app.py", line 14, in <module>
    from .player import Player
  File "/usr/local/lib/python3.6/site-packages/feeluown-1.1.0-py3.6.egg/feeluown/player.py", line 10, in <module>
    from fuocore.core.player import MpvPlayer
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/fuocore-1.1.0-py3.6.egg/fuocore/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/fuocore-1.1.0-py3.6.egg/fuocore/core/player.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/fuocore-1.1.0-py3.6.egg/mpv.py", line 229, in <module>
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, mpv_client_api_version): symbol not found

**Comment by cosven** [comment]
你的 mpv 是什么版本呀? `mpv --version` 可以查看

**Comment by cosven** [comment]
先 close 了
