### ISSUE TITLE
ubuntu 14.04 unable to install libmpv1 

### ISSUE THREAD

**Issue by lexusking** [cosven/FeelUOwn#234]
ubuntu 14.04 unable to install libmpv1 . I try many times and try to download some deb package to install by myself . But I find the lib depens many other packages .

So,how to resolve this problem? 

And  can you give a version  which isn't  denpens by libmpv1.

**Comment by cosven** [comment]
> But I find the lib depens many other packages .
Yes, the libmpv1 package may depend on some other packages. A deb package will work for specific Linux Distribution.

You can first try this instruction: http://linuxg.net/how-to-install-mpv-on-ubuntu-14-04-trusty-tahr-ubuntu-13-10-saucy-salamander-and-linux-mint-16-petra/

**Comment by lexusking** [comment]
I install the mpv lib succuss, but when execute the program ,throws this exception

liuwx@T420:~$ feeluown
Traceback (most recent call last):
  File "/home/liuwx/.local/bin/feeluown", line 9, in <module>
    load_entry_point('feeluown==2.0.2', 'console_scripts', 'feeluown')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/liuwx/.local/lib/python3.4/site-packages/feeluown/__main__.py", line 11, in <module>
    from fuocore.app import run_server
  File "/home/liuwx/.local/lib/python3.4/site-packages/fuocore/__init__.py", line 5, in <module>
    from fuocore.player import (
  File "/home/liuwx/.local/lib/python3.4/site-packages/fuocore/player.py", line 26, in <module>
    from mpv import MPV, MpvEventID, MpvEventEndFile, \
  File "/home/liuwx/.local/lib/python3.4/site-packages/mpv.py", line 229, in <module>
    backend.mpv_client_api_version.restype = c_ulong
  File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: mpv_client_api_version

**Comment by cosven** [comment]
已经在 tg 群中讨论（结论是需要自己编译，或者找一个能用的 libmpv1 包安装）
