### ISSUE TITLE
Netease cloud music can't play my favorite music.

### ISSUE THREAD

**Issue by Zangwill** [cosven/FeelUOwn#240]
点击“喜欢的音乐”无反映，debug 模式中点击时输出的日志为：

```
[ERROR] [__init__ __log_error 589] : Task exception was never retrieved
future: <Task finished coro=<LeftPanel.show_model() done, defined at /usr/local/lib/python3.6/site-packages/feeluown/ui.py:240> exception=ValidationError({'tracks': {94: {'album': {'name': ['Field may not be null.']}}}},)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/feeluown/ui.py", line 241, in show_model
    await self._app.ui.table_container.show_model(playlist)
  File "/usr/local/lib/python3.6/site-packages/feeluown/containers/table_container.py", line 165, in show_model
    await func(model)
  File "/usr/local/lib/python3.6/site-packages/feeluown/containers/table_container.py", line 175, in show_playlist
    songs = await loop.run_in_executor(None, lambda: playlist.songs)
  File "/usr/local/lib/python3.6/site-packages/quamash/__init__.py", line 87, in run
    r = callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/feeluown/containers/table_container.py", line 175, in <lambda>
    songs = await loop.run_in_executor(None, lambda: playlist.songs)
  File "/usr/local/lib/python3.6/site-packages/fuocore/netease/models.py", line 37, in __getattribute__
    obj = cls.get(self.identifier)
  File "/usr/local/lib/python3.6/site-packages/fuocore/netease/models.py", line 190, in get
    playlist, _ = NeteasePlaylistSchema(strict=True).load(data)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 576, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/lib/python3.6/site-packages/marshmallow/schema.py", line 699, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'tracks': {94: {'album': {'name': ['Field may not be null.']}}}}
```

**Comment by cosven** [comment]
这是个 bug，我今明两天尽量修复一下。

原因是：网易云音乐 API 返回的歌单数据中的一首歌的专辑名字为 null，但之前程序默认要求这个字段不能为 null。

**Comment by cosven** [comment]
你可以提供一下你的网易云音乐的个人主页么，或者自己的用户 ID，我用你的播放列表测试一下。
我自己找了几个播放列表和歌曲，都没有找到 Album 为空的歌曲。

**Comment by Zangwill** [comment]
<https://music.163.com/#/my/m/music/playlist?id=327598494>
