### ISSUE TITLE
Emacs中搜索到的列表，回车与空格都报错

### ISSUE THREAD

**Issue by peng051410** [cosven/FeelUOwn#245]
在Emacs中使用时，播放时后台程序报错如下：
`Traceback (most recent call last):
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/__init__.py", line 68, in exec_cmd
    cmd_rv = handler.handle(cmd)
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/show.py", line 127, in handle
    raise Exception('uri 不能被正确识别')
Exception: uri 不能被正确识别
[ERROR] [__init__ exec_cmd 72] : handle cmd(action:play args:('fuo',)) error
Traceback (most recent call last):
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/__init__.py", line 68, in exec_cmd
    cmd_rv = handler.handle(cmd)
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/handlers.py", line 70, in handle
    return self.play_song(song_furi)
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/handlers.py", line 87, in play_song
    song = provider.Song.get(identifier)
AttributeError: 'NoneType' object has no attribute 'Song'
[ERROR] [__init__ exec_cmd 72] : handle cmd(action:play args:('fuo',)) error
Traceback (most recent call last):
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/__init__.py", line 68, in exec_cmd
    cmd_rv = handler.handle(cmd)
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/handlers.py", line 70, in handle
    return self.play_song(song_furi)
  File "/Users/tomyli/Library/Python/3.7/lib/python/site-packages/feeluown/protocol/handlers.py", line 87, in play_song
    song = provider.Song.get(identifier)
AttributeError: 'NoneType' object has no attribute 'Song'`

**Comment by cosven** [comment]
这个得看下实际的情况才能判断是哪里的问题，感觉是遇到什么特殊情况了。我刚本地试了下，在一首歌上按 Enter 是可以的。

> 连接搜索到的列表

另外，我没有太了解这个是指什么。

**Comment by cosven** [comment]
我自己测试的 case 是搜周杰伦，然后按 Enter 播放，有的歌曲可以播放成功，有的歌曲不能播放（Invalid Song 的问题），但是没有出现上面这个情况。

**Comment by peng051410** [comment]
我也是测试的周杰伦，下面是搜索到的结果列表
![image](https://user-images.githubusercontent.com/5512326/46916682-69448900-cff0-11e8-9e43-d1619b4fd2a2.png)
然后我选择“屋顶”进行播放，就出现这个错误了
![image](https://user-images.githubusercontent.com/5512326/46916693-95f8a080-cff0-11e8-9bda-ec45c8a8850f.png)
感觉是和
packages/feeluown/protocol/handlers.py", line 87, in play_song song = provider.Song.get(identifier) AttributeError: 'NoneType' object has no attribute 'Song'
这个有关吧，需要我再提供其它的信息不？

**Comment by peng051410** [comment]
我试了一下，`emacs -Q`确实可以，我自己找一下问题吧，谢谢！
