### ISSUE TITLE
ubuntu 14.04 unable to install libmpv1(新手卡在了这里)

### ISSUE THREAD

**Issue by w316525096** [cosven/FeelUOwn#266]
新手求助.
 环境:ubuntu server 14.04
#234  
#https://github.com/cosven/FeelUOwn/issues/234#issuecomment-410604474  已尝试安装.

 命令行中启动,输出
```
Traceback (most recent call last):
  File "./feeluown", line 9, in <module>
    load_entry_point('feeluown==3.0a6', 'console_scripts', 'feeluown')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/ubuntuvnc/.local/lib/python3.4/site-packages/feeluown/__main__.py", line 11, in <module>
    from fuocore.dispatch import Signal
  File "/home/ubuntuvnc/.local/lib/python3.4/site-packages/fuocore/__init__.py", line 2, in <module>
    from fuocore.player import (
  File "/home/ubuntuvnc/.local/lib/python3.4/site-packages/fuocore/player.py", line 27, in <module>
    from mpv import MPV, MpvEventID, MpvEventEndFile, \
  File "/home/ubuntuvnc/.local/lib/python3.4/site-packages/mpv.py", line 639
    _1, _2, _3, pointer = _make_node_str_list([name, *args])
                                                           ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by cosven** [comment]
非常抱歉，feeluown 目前只支持 Python 3.5/3.6/3.7，不支持 Python 3.4。
我知道 Ubuntu 14.04 自带的 Python 3 版本可能比较低，我搜索了一下，有两种办法可以安装新版 Python。

**1. 安装 Python 3.6 -> 参考这个回答 https://askubuntu.com/a/865569**

添加一个源，然后安装 Python 3.6，我自己没有真正尝试过这个方案，但看起来还是挺靠谱的。操作起来也比较简单。

**2. 使用 pyenv 安装多个 Python**

[pyenv](https://github.com/pyenv/pyenv) 也是个不错的工具，我之前自己在其他系统上试用过。但是相对第一种方案，这个方法稍微麻烦一点。

**Comment by w316525096** [comment]
> 非常抱歉，feeluown 目前只支持 Python 3.5/3.6/3.7，不支持 Python 3.4。
> 
> 所以解决这个问题的思路是：安装一个新版本的 Python，理论上版本 >=3.5 即可，但是我强烈推荐安装 Python 3.6 或者 Python 3.7。
> 
> 我知道 Ubuntu 14.04 自带的 Python 3 版本可能比较低，我搜索了一下，有两种办法可以安装新版 Python。
> 
> **1. 安装 Python 3.6 -> 参考这个回答 https://askubuntu.com/a/865569**
> 
> 添加一个源，然后安装 Python 3.6，我自己没有真正尝试过这个方案，但看起来还是挺靠谱的。操作起来也比较简单。
> 
> **2. 使用 pyenv 安装多个 Python**
> 
> [pyenv](https://github.com/pyenv/pyenv) 也是个不错的工具，我之前自己在其他系统上试用过。但是相对第一种方案，这个方法稍微麻烦一点。

thank you !
