### ISSUE TITLE
为啥点登陆没反应

### ISSUE THREAD

**Issue by fulvaz** [cosven/FeelUOwn#35]
装过旧版,没问题,后来卸载了

今天装了最新版,其他功能正常,就是不能登陆

**Comment by sandnon** [comment]
我点击登录崩溃了。
`widgets/login_dialog.py:49`，parent里的api被重构没了。临时改成`self.ne = ControllerApi.api`可以使用

**Comment by fulvaz** [comment]
```NameError: name 'ControllerApi' is not defined```
....临时方案也不行

---------------------------------------
附上log....嗯,第一次报bug,好紧张

```
fulva@ubuntu:~/Programs/FeelUOwn$ ./app.sh 
[INFO] [__init__.py line:41] : Using Qt Implementation: PyQt5
[INFO] [__init__.py line:19] : NetEase Plugin init
[INFO] [__init__.py line:39] : 找不到您的cookies文件，请您手动登录
[ERROR] [__init__.py line:593] : Exception in callback <bound method Controller._init_plugins of <controllers.Controller object at 0x7faeaf60cdc8>>()
handle: Handle(<bound method Controller._init_plugins of <controllers.Controller object at 0x7faeaf60cdc8>>, ())
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 39, in _run
    self._callback(*self._args)
  File "/home/fulva/Programs/FeelUOwn/src/controllers.py", line 58, in _init_plugins
    Hotkey.init()
  File "/home/fulva/Programs/FeelUOwn/src/plugin/Hotkey/__init__.py", line 18, in init
    event = KeyEventLoop(ControllerApi.player)
  File "/home/fulva/Programs/FeelUOwn/src/plugin/Hotkey/linux.py", line 30, in __init__
    self.disp = Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
Traceback (most recent call last):
  File "/home/fulva/Programs/FeelUOwn/src/controllers.py", line 141, in pop_login
    w = LoginDialog(self)
  File "/home/fulva/Programs/FeelUOwn/src/widgets/login_dialog.py", line 48, in __init__
    self.ne = parent.api
AttributeError: 'Controller' object has no attribute 'api'
```

**Comment by sandnon** [comment]
```
from interfaces import ControllerApi
```
上面要导入`ControllerApi`

放松放松 : )

**Comment by fulvaz** [comment]
3q~ 问题解决

总结一下,临时的解决方案是
用编辑器打开```src/widgets/login_dialog.py```
在文件开头导入 ```from interfaces import ControllerApi```
转到第50行 修改```self.ne = parent.api```为```self.ne = ControllerApi.api```

----------------------

题外话
各位遇到问题可以用命令行运行```./app.sh```, 然后将log贴出来,方便解决问题

**Comment by cosven** [comment]
确实确实。

最新在探究新的代码结构，想让开发者可以更加方便的开发插件，所以改动了一些东西，然而测试用例覆盖率非常的低...所以有一些问题...

感谢 @fulvaz 的这个解决方案。 bug的修复基本也是这个思路

**Comment by cosven** [comment]
感谢 @sandnon
