### ISSUE TITLE
Ubuntu 15.10 播放器不能运行

### ISSUE THREAD

**Issue by mensyli** [cosven/FeelUOwn#51]
Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    from quamash import QEventLoop
ImportError: No module named 'quamash'
提示这个错误

**Comment by cosven** [comment]
你没有安装相关的依赖。<https://github.com/cosven/FeelUOwn#目前依賴> 

如果`pip3 install -r requirements.txt` 这条命令没有错误的话，就不会有这个问题了。

**Comment by Lycreal** [comment]
同样出现这个错误，执行pip3 install -r requirements.txt提示
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'

**Comment by cosven** [comment]
理论上来讲，不需要先删除，再执行updat.sh。
https://github.com/cosven/FeelUOwn/blob/master/install.sh#L62 这句应该保证能覆盖之前的文件的。
@Lycreal

**Comment by cosven** [comment]
错误的原因同 #54

**Comment by CortYellow** [comment]
问题解决，先删除桌面图标，然后运行./update.h 即可。
谢谢@cosven   @Lycreal

**Comment by Lycreal** [comment]
@cosven wiki不对吧，并不是PyQt5组件的问题，
而是执行```pip3(或pip?) install -r requirements.txt```时，quamash安装给了python3.5。
如果执行```sudo easy_install3 pip```后再执行```pip3 install -r requirements.txt```，
就可以用```python3.4(和python3) main.py```来启动程序了。（在我的机器上）

**Comment by cosven** [comment]
恩，关键就是搞清楚 `pip3` 到底是哪个版本python的。
看你们的描述，应该不是pyqt的问题，稍微改了下wiki...
