### ISSUE TITLE
点击包含歌曲较多的歌单就闪退

### ISSUE THREAD

**Issue by abcfy2** [cosven/FeelUOwn#66]
```
╰─$ ./app.sh 
[INFO] [__init__.py line:41] : Using Qt Implementation: PyQt5
[INFO] [controllers.py line:50] : db connected: /home/fengyu/.FeelUOwn/cache/data.db
[INFO] [__init__.py line:15] : NetEase Plugin init
[INFO] [api.py line:37] : method=POST_UPDATE url=http://music.163.com/api/push/init query={}
[INFO] [connectionpool.py line:264] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:67] : Save user cookies
[INFO] [normalize.py line:72] : Save user login time
<class 'Xlib.protocol.request.QueryExtension'>
[INFO] [normalize.py line:148] : Read playlist 53122581 info from sqlite
[INFO] [normalize.py line:148] : Read playlist 123056695 info from sqlite
[INFO] [normalize.py line:148] : Read playlist 120899665 info from sqlite
[INFO] [version_manager.py line:16] : 正在查找新版本...
[INFO] [connectionpool.py line:716] : Starting new HTTPS connection (1): api.github.com
[INFO] [normalize.py line:148] : Read playlist 53122581 info from sqlite
[INFO] [api.py line:37] : method=GET url=http://music.163.com/api/song/detail/?id=26434737&ids=[26434737] query=None
[INFO] [connectionpool.py line:264] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:142] : Save music 26434737 info into sqlite
[INFO] [normalize.py line:148] : Read playlist 53122581 info from sqlite
[INFO] [version_manager.py line:16] : 正在查找新版本...
[INFO] [connectionpool.py line:716] : Starting new HTTPS connection (1): api.github.com
```

没有细看代码，不确定是否因为某些操作是同步的，阻塞了窗口事件？
日志中有连接github的部分，一旦出现这些日志的时候，窗体就会点不动，点击关闭按钮还会弹出窗口无响应，是否强制关闭的选项。

**Comment by abcfy2** [comment]
一旦连接超时，程序会立刻崩溃退出。这个异常没捕获么？
建议这里改用异步的方式处理，否则等待检测github新版本的时候主窗口就直接卡住了。

```
[ERROR] [__init__.py line:597] : Exception in callback VersionManager.check_feeluown_release()
handle: <Handle VersionManager.check_feeluown_release()>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 562, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 111, in connect
    timeout=self.timeout)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] 连接超时

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 612, in urlopen
    raise MaxRetryError(self, url, e)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cosven/FeelUOwn/releases (Caused by <class 'TimeoutError'>: [Errno 110] 连接超时)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/home/fengyu/projects/FeelUOwn/src/c/version_manager.py", line 17, in check_feeluown_release
    res = requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cosven/FeelUOwn/releases (Caused by <class 'TimeoutError'>: [Errno 110] 连接超时)
```

**Comment by cosven** [comment]
这样子， 我今天看看 - -。

**Comment by abcfy2** [comment]
嗯。我以前也用pyqt写过界面。总之尽量不要阻塞主窗体循环事件，否则会卡住窗口。
有需要长时间执行的操作，单独扔到后台worker执行。最后就是，尽可能多的捕获异常，不要让主窗体挂掉，可以在断网情况下测试

**Comment by LER0ever** [comment]
我也有这样的问题！不过我出错原因不一样，可能是歌单太多，一点到很多歌曲的歌单就闪退。
```
[INFO] [connectionpool.py line:207] : Starting new HTTP connection (1): music.163.com
[INFO] [api.py line:35] : method=GET url=http://music.163.com/api/playlist/detail?id=3317200&offset=0&total=true&limit=1001 query=None
[INFO] [connectionpool.py line:207] : Starting new HTTP connection (1): music.163.com
Traceback (most recent call last):
  File "/usr/share/feeluown-git/src/view_api.py", line 200, in on_playlist_btn_clicked
    pid, cache=False)
  File "/usr/share/feeluown-git/src/plugin/NetEaseMusic/normalize.py", line 182, in get_playlist_detail
    return self.update_playlist_detail(pid)
  File "/usr/share/feeluown-git/src/plugin/NetEaseMusic/normalize.py", line 161, in update_playlist_detail
    if PlaylistDb.exists(pid):
  File "/usr/share/feeluown-git/src/plugin/NetEaseMusic/model.py", line 42, in exists
    if ControllerApi.session.query(cls).filter(cls.pid==pid).count() > 0:
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2951, in count
    return self.from_self(col).scalar()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2720, in scalar
    ret = self.one()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2689, in one
    ret = list(self)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2732, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2745, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2736, in _connection_from_session
    **kw)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 905, in connection
    execution_options=execution_options)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 910, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 202, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
fish: “python3 main.py” terminated by signal SIGABRT (Abort)

```

**Comment by cosven** [comment]
很久之前的 issue 了，现在不以来 sql 查询了，先 close 了。
