### ISSUE TITLE
Something wrong with PyQt5

### ISSUE THREAD

**Issue by duoduoeeee** [cosven/FeelUOwn#74]
之前版本的软件运行得非常好 今天想升级到最新版 但是升级之后报错 我是这么做的

1. 在安装目录 /opt/FeelUOwn下运行了uninstall.sh，报卸载完毕
2. 删除了FeelUOwn的目录
3. 用git下载了新的版本还放到了FeelUOwn目录下，运行了install.sh，输出如下
```
---------------------------
脚本适用于Debian系的Linux
---------------------------
安装系统软件依赖
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-xlib is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5.qtmultimedia is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5.qtwebkit is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5multimedia5-plugins is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer0.10-plugins-good is already the newest version.
gstreamer0.10-plugins-bad is already the newest version.
gstreamer0.10-plugins-ugly is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gstreamer1.0-plugins-good is already the newest version.
gstreamer1.0-libav is already the newest version.
gstreamer1.0-plugins-bad is already the newest version.
gstreamer1.0-plugins-ugly is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
安装系统依赖完毕
准备安装相关python依赖
您的系统目前没有安装pip3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
install pip for python3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
---------------------------
生成桌面图标
猜测：英文系统
生成系统图标
===============================
VLC播放器可以用来播放MV，您还没有安装过，如果您使用Ubuntu，建议您安装它；如果您使用Deepin，你可以不安装
现在为您安装VLC播放器吗 ？
确认: 'y/n'
> n
取消安装 VLC播放器
全部完成!
lingduo@lingduo-linux-pc:/opt/FeelUOwn-master$ 

```

说我没装pip3 我是在有python3.4的情况下 源码安装了python3.5，系统现在有python3.5：
![image](https://cloud.githubusercontent.com/assets/14347369/12006951/8bc6f2ae-ac28-11e5-9094-952ef720ea44.png)

然后在运行app.sh的时候 报如下错误：
```
lingduo@lingduo-linux-pc:/opt/FeelUOwn-master$ ./app.sh 
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named 'PyQt5'
lingduo@lingduo-linux-pc:/opt/FeelUOwn-master$ 
```

我安装了`python-pyqt*`和`python3-pyqt*`，但是装完后仍报同样错 双击桌面图标或点击dash图标均无反应 

系统是ubuntu15.10的64位版

跪求大神解决

**Comment by cosven** [comment]
可以试试 
- `sudo apt-get remove python3-pip`
- `sudo easy_install3 pip3`, 然后再次运行 `install.sh`

**Comment by duoduoeeee** [comment]
```
lingduo@lingduo-linux-pc:/opt/FeelUOwn$ sudo easy_install3.4 pip3
sudo: easy_install3.4: command not found

lingduo@lingduo-linux-pc:/opt/FeelUOwn$ sudo easy_install3 pip3
Searching for pip3
Reading https://pypi.python.org/simple/pip3/
Couldn't find index page for 'pip3' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pip3
error: Could not find suitable distribution for Requirement.parse('pip3')
```

。。。。

**Comment by duoduoeeee** [comment]
诶 运行python3.4 feeluown/main.py
好了能用了
只是为嘛我的python3.5不能用。。。

**Comment by cosven** [comment]
`easy_install-3.4`
你应该试试用tab键补全的. 😁

**Comment by duoduoeeee** [comment]
谢谢大神 快捷方式我自己改好了

**Comment by cosven** [comment]
只是系统默认选择了 Python3.4 作为默认版本了，所以那些库都默认安装到了3.4当中去了。
至于系统为啥选择了3.4，这个问题我也不是很清楚，但是大概的原因就是你自己编译安装了3.5的源码。（这个我也不确定。）

快捷方式_可能_会有坑，不能只修改桌面的那个文件，因为那样的话，你在dash中搜索，就不能运行了。最好修改下 `install.sh` 文件，python3.5 改为 3.4。目测你应该可以轻松搞定。

**Comment by duoduoeeee** [comment]
哦 我改的就是dash里的那个 桌面上的删除了 我一向习惯用dash搜索 再次跪谢大神

**Comment by cosven** [comment]
Soga, 看来我想多了 ...

**Comment by eallion** [comment]
解决了

**Comment by gera2ld** [comment]
源码编译很多坑，可以试下[pyenv](https://github.com/yyuu/pyenv)
