### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by llq520** [cosven/FeelUOwn#89]
无法创建歌单，导致试听列表无法保存 创建的歌单旁加号不可用

这里是终端反馈信息

[INFO] [api.py line:36] : method=POST url=http://music.163.com/api/playlist/create query={'name': 'default', 'uid': 0}
[INFO] [connectionpool.py line:205] : Starting new HTTP connection (1): music.163.com

我无法登录163帐号

[INFO] [connectionpool.py line:205] : Starting new HTTP connection (1): music.163.com
Traceback (most recent call last):
  File "../feeluown/widgets/login_dialog.py", line 117, in __login
    data = self.ne.login(username, password, phone_login)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 92, in login
    data = self.access_data_user(data)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 419, in access_data_user
    user_data['avatar'] = user_data['profile']['avatarUrl']
KeyError: 'profile'

**Comment by cosven** [comment]
你需要在网页上完善自己的信息。<http://music.163.com/#/user/update>

**Comment by cosven** [comment]
#48 也是一样的情况。
