### ISSUE TITLE
搜索歌曲框无法使用搜狗输入法

### ISSUE THREAD

**Issue by abcfy2** [cosven/FeelUOwn#91]
OS: LinuxMint 17.3 cinnamon DE
使用输入法: 搜狗拼音(fcitx框架)

现在发现在搜索歌曲这个输入框怎么按也无法使用中文输入法，只能输入英文，但是浏览器打字，终端敲字都是正常的。

**Comment by abcfy2** [comment]
终端启动的时候还会抛一个异常:

```
╰─$ ./app.sh 
[INFO] [utils.py line:57] : function __init__ executed time: 0.013789 s
[INFO] [controllers.py line:55] : db connected: /home/fengyu/.FeelUOwn/cache/data.db
[INFO] [utils.py line:57] : function __init__ executed time: 0.069944 s
[INFO] [version_manager.py line:19] : 正在查找新版本...
[INFO] [connectionpool.py line:716] : Starting new HTTPS connection (1): api.github.com
[INFO] [__init__.py line:15] : NetEase Plugin init
[INFO] [api.py line:36] : method=POST_UPDATE url=http://music.163.com/api/push/init query={}
[INFO] [connectionpool.py line:264] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:70] : Save user cookies
[INFO] [normalize.py line:75] : Save user login time
[INFO] [api.py line:36] : method=GET url=http://music.163.com/api/user/playlist/?offset=0&limit=200&uid=54759481 query=None
[INFO] [connectionpool.py line:264] : Starting new HTTP connection (1): music.163.com
[INFO] [normalize.py line:179] : Read playlist 53122581 info from sqlite
[INFO] [view_api.py line:193] : load user infos finished
[INFO] [utils.py line:57] : function load_user_infos executed time: 0.013800 s
<class 'Xlib.protocol.request.QueryExtension'>
[INFO] [normalize.py line:209] : update user playlists info
[ERROR] [__init__.py line:597] : Exception in callback NetEaseAPI.get_playlist_detail(123056695)
handle: <Handle NetEaseAPI.get_playlist_detail(123056695)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "../feeluown/plugin/NetEaseMusic/normalize.py", line 178, in get_playlist_detail
    if PlaylistDb.exists(pid):
  File "../feeluown/plugin/NetEaseMusic/model.py", line 42, in exists
    if ControllerApi.session.query(cls).filter(cls.pid==pid).count() > 0:
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2790, in count
    return self.from_self(col).scalar()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2559, in scalar
    ret = self.one()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2528, in one
    ret = list(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2584, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 2575, in _connection_from_session
    **kw)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 202, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
[INFO] [normalize.py line:179] : Read playlist 120899665 info from sqlite
```

**Comment by cosven** [comment]
#20  这个问题貌似是类似的。
你试试安装这个安这个包  `fcitx-front-qt5`

**Comment by abcfy2** [comment]
果然是，安装之后就解决了。
包名应该是``fcitx-frontend-qt5``

**Comment by abcfy2** [comment]
这次终端启动也没有这个异常了

**Comment by cosven** [comment]
这个异常是关于数据库的，出现的几率应该较小。出现的原因我也没去研究过...

**Comment by cosven** [comment]
c11a8ecccb8c45363e661d8bd0ccef5c53b6d0b7

这个异常在这个 PR 中应该解决了。
