### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by xuhao148** [cosven/FeelUOwn#95]
Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    from feeluown.controllers import Controller
  File "../feeluown/controllers.py", line 33, in <module>
    from feeluown.plugin import NetEaseMusic, Hotkey, MprisEx
  File "../feeluown/plugin/MprisEx/__init__.py", line 5, in <module>
    import dbus.mainloop.pyqt5
ImportError: No module named 'dbus.mainloop.pyqt5'

**Comment by cosven** [comment]
`sudo apt-get install python3-dbus.mainloop.pyqt5`

不好意思，忘记这个依赖了。
